version: 2
updates:
  # When a new version of action exists
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        # Patch and minor updates don't matter for libraries
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
